export interface ImageResponseData {
  access_mode: string,
  asset_id: string,
  created_at: string,
  etag: string,
  format: string,
  original_extension: string,
  original_filename: string,
  public_id: string,
  resource_type: string,
  secure_url: string,
  signature: string,
  type: string,
  url: string,
  version_id: string,
  placeholder: false,
  tags: [],
  height: number,
  bytes: number,
  version: number,
  width: number,
}
export interface VideoResponseData {
  audio: {
    bit_rate: string,
    channel_layout: string,
    codec: string,
    channels: number,
    frequency: number,
  }
  bit_rate: number,
  bytes: number,
  duration: number,
  frame_rate: number,
  height: number,
  nb_frames: number,
  pages: number,
  rotation: number,
  version: number,
  width: number,
  is_audio: boolean
  placeholder: boolean
  access_mode: string,
  asset_id: string,
  created_at: string,
  etag: string,
  format: string,
  original_filename: string,
  public_id: string,
  resource_type: string,
  secure_url: string,
  signature: string,
  tags: [],
  type: string,
  url: string,
  version_id: string,
  video: {
    bit_rate: string,
    codec: string,
    dar: string,
    pix_format: string,
    profile: string,
    time_base: string,
    level: number
  }
}